--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2
-- Dumped by pg_dump version 15.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO postgres;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_emailverified; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_emailverified (
    id bigint NOT NULL,
    is_verified boolean NOT NULL,
    verification_date timestamp with time zone,
    verfication_token character varying(100) NOT NULL,
    user_id bigint NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.accounts_emailverified OWNER TO postgres;

--
-- Name: accounts_emailverified_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_emailverified ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_emailverified_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_otp; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_otp (
    id bigint NOT NULL,
    code character varying(6) NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    is_verified boolean NOT NULL,
    service_id bigint,
    user_id bigint
);


ALTER TABLE public.accounts_otp OWNER TO postgres;

--
-- Name: accounts_otp_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_otp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_otp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_passwordchangerequested; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_passwordchangerequested (
    id bigint NOT NULL,
    is_requested boolean NOT NULL,
    user_id bigint
);


ALTER TABLE public.accounts_passwordchangerequested OWNER TO postgres;

--
-- Name: accounts_passwordchangerequested_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_passwordchangerequested ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_passwordchangerequested_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(20) NOT NULL,
    is_service_provider boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    is_superuser boolean NOT NULL
);


ALTER TABLE public.accounts_user OWNER TO postgres;

--
-- Name: accounts_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.accounts_user_groups OWNER TO postgres;

--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.accounts_user_user_permissions OWNER TO postgres;

--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO postgres;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: events_event; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.events_event (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    total_cost numeric(10,2) NOT NULL,
    location_id bigint NOT NULL,
    user_id bigint NOT NULL,
    event_type_id bigint,
    other_type character varying(255)
);


ALTER TABLE public.events_event OWNER TO postgres;

--
-- Name: events_event_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.events_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: events_eventtype; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.events_eventtype (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.events_eventtype OWNER TO postgres;

--
-- Name: events_eventtype_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.events_eventtype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_eventtype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: events_invitationcard; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.events_invitationcard (
    id bigint NOT NULL,
    invitation text NOT NULL,
    event_id bigint NOT NULL
);


ALTER TABLE public.events_invitationcard OWNER TO postgres;

--
-- Name: events_invitationcard_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.events_invitationcard ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_invitationcard_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: events_reservation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.events_reservation (
    id bigint NOT NULL,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    status character varying(20) NOT NULL,
    cost numeric(10,2) NOT NULL,
    event_id bigint NOT NULL,
    service_id bigint NOT NULL
);


ALTER TABLE public.events_reservation OWNER TO postgres;

--
-- Name: events_reservation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.events_reservation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_reservation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: locations_address; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.locations_address (
    id bigint NOT NULL,
    street character varying(255),
    village_city character varying(100),
    state character varying(100),
    country character varying(100)
);


ALTER TABLE public.locations_address OWNER TO postgres;

--
-- Name: locations_address_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.locations_address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.locations_address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: locations_location; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.locations_location (
    id bigint NOT NULL,
    latitude numeric(12,9) NOT NULL,
    longitude numeric(12,9) NOT NULL,
    address_id bigint NOT NULL
);


ALTER TABLE public.locations_location OWNER TO postgres;

--
-- Name: locations_location_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.locations_location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.locations_location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications_message; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications_message (
    id bigint NOT NULL,
    message text NOT NULL
);


ALTER TABLE public.notifications_message OWNER TO postgres;

--
-- Name: notifications_message_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications_notification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications_notification (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    dest_id bigint NOT NULL,
    message_id bigint NOT NULL,
    source_id bigint NOT NULL
);


ALTER TABLE public.notifications_notification OWNER TO postgres;

--
-- Name: notifications_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: photos_decorphotos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.photos_decorphotos (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    uploaded_at timestamp with time zone,
    decor_id bigint NOT NULL
);


ALTER TABLE public.photos_decorphotos OWNER TO postgres;

--
-- Name: photos_decorphotos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.photos_decorphotos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.photos_decorphotos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: photos_foodphotos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.photos_foodphotos (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    uploaded_at timestamp with time zone,
    food_id bigint NOT NULL
);


ALTER TABLE public.photos_foodphotos OWNER TO postgres;

--
-- Name: photos_foodphotos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.photos_foodphotos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.photos_foodphotos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: photos_maindecorphoto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.photos_maindecorphoto (
    id bigint NOT NULL,
    decor_id bigint NOT NULL,
    "decorPhoto_id" bigint NOT NULL
);


ALTER TABLE public.photos_maindecorphoto OWNER TO postgres;

--
-- Name: photos_maindecorphoto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.photos_maindecorphoto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.photos_maindecorphoto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: photos_mainfoodphoto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.photos_mainfoodphoto (
    id bigint NOT NULL,
    food_id bigint NOT NULL,
    "foodPhoto_id" bigint NOT NULL
);


ALTER TABLE public.photos_mainfoodphoto OWNER TO postgres;

--
-- Name: photos_mainfoodphoto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.photos_mainfoodphoto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.photos_mainfoodphoto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: photos_servicephotos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.photos_servicephotos (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    uploaded_at timestamp with time zone,
    service_id bigint NOT NULL
);


ALTER TABLE public.photos_servicephotos OWNER TO postgres;

--
-- Name: photos_servicephotos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.photos_servicephotos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.photos_servicephotos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: photos_serviceprofilephoto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.photos_serviceprofilephoto (
    id bigint NOT NULL,
    service_id bigint NOT NULL,
    "servicePhoto_id" bigint NOT NULL
);


ALTER TABLE public.photos_serviceprofilephoto OWNER TO postgres;

--
-- Name: photos_serviceprofilephoto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.photos_serviceprofilephoto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.photos_serviceprofilephoto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reports_reportreview; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reports_reportreview (
    id bigint NOT NULL,
    reason text NOT NULL,
    is_solved boolean NOT NULL,
    reporter_id bigint NOT NULL,
    review_id bigint NOT NULL,
    solved_by_id bigint
);


ALTER TABLE public.reports_reportreview OWNER TO postgres;

--
-- Name: reports_reportreview_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reports_reportreview ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reports_reportreview_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reports_reportservice; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reports_reportservice (
    id bigint NOT NULL,
    reason text NOT NULL,
    evidence character varying(100),
    resolution character varying(255),
    is_solved boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    reporter_id bigint NOT NULL,
    service_id bigint NOT NULL,
    solved_by_id bigint
);


ALTER TABLE public.reports_reportservice OWNER TO postgres;

--
-- Name: reports_reportservice_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reports_reportservice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reports_reportservice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reviews_review; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reviews_review (
    id bigint NOT NULL,
    rating integer NOT NULL,
    comment text,
    created_at timestamp with time zone NOT NULL,
    service_id bigint NOT NULL,
    user_id bigint NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.reviews_review OWNER TO postgres;

--
-- Name: reviews_review_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reviews_review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_booking; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_booking (
    id bigint NOT NULL,
    date date NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    service_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.services_booking OWNER TO postgres;

--
-- Name: services_booking_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_booking ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_decor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_decor (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    quantity integer NOT NULL,
    available_quantity integer NOT NULL,
    hourly_rate numeric(10,2),
    description text,
    decor_service_id bigint NOT NULL,
    price numeric(10,2)
);


ALTER TABLE public.services_decor OWNER TO postgres;

--
-- Name: services_decor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_decor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_decor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_decorationservice; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_decorationservice (
    service_ptr_id bigint NOT NULL,
    area_limit_km integer
);


ALTER TABLE public.services_decorationservice OWNER TO postgres;

--
-- Name: services_decoreventtype; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_decoreventtype (
    id bigint NOT NULL,
    event_type_id bigint NOT NULL,
    decor_id bigint NOT NULL
);


ALTER TABLE public.services_decoreventtype OWNER TO postgres;

--
-- Name: services_decoretype_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_decoreventtype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_decoretype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_djservice; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_djservice (
    service_ptr_id bigint NOT NULL,
    music_genre character varying(255),
    equipment_provided text,
    hourly_rate numeric(10,2),
    area_limit_km integer
);


ALTER TABLE public.services_djservice OWNER TO postgres;

--
-- Name: services_entertainementservice; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_entertainementservice (
    service_ptr_id bigint NOT NULL,
    hourly_rate numeric(10,2),
    area_limit_km integer
);


ALTER TABLE public.services_entertainementservice OWNER TO postgres;

--
-- Name: services_favoriteservice; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_favoriteservice (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    service_id bigint NOT NULL
);


ALTER TABLE public.services_favoriteservice OWNER TO postgres;

--
-- Name: services_favoriteservice_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_favoriteservice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_favoriteservice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_food; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_food (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    price double precision NOT NULL,
    food_type_id bigint NOT NULL,
    ingredients text
);


ALTER TABLE public.services_food OWNER TO postgres;

--
-- Name: services_food_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_food ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_food_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_foodservice; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_foodservice (
    service_ptr_id bigint NOT NULL,
    area_limit_km integer
);


ALTER TABLE public.services_foodservice OWNER TO postgres;

--
-- Name: services_foodservicefood; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_foodservicefood (
    id bigint NOT NULL,
    food_id bigint NOT NULL,
    "foodService_id" bigint NOT NULL
);


ALTER TABLE public.services_foodservicefood OWNER TO postgres;

--
-- Name: services_foodservicefood_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_foodservicefood ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_foodservicefood_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_foodtype; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_foodtype (
    id bigint NOT NULL,
    type character varying(255) NOT NULL
);


ALTER TABLE public.services_foodtype OWNER TO postgres;

--
-- Name: services_foodtype_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_foodtype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_foodtype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_foodtypeservice; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_foodtypeservice (
    id bigint NOT NULL,
    "foodService_id" bigint NOT NULL,
    "foodType_id" bigint NOT NULL
);


ALTER TABLE public.services_foodtypeservice OWNER TO postgres;

--
-- Name: services_foodtypeservice_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_foodtypeservice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_foodtypeservice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_photographerservice; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_photographerservice (
    service_ptr_id bigint NOT NULL,
    hourly_rate numeric(10,2),
    area_limit_km integer
);


ALTER TABLE public.services_photographerservice OWNER TO postgres;

--
-- Name: services_service; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_service (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    service_provider_id bigint NOT NULL,
    service_type_id bigint NOT NULL,
    created_at timestamp with time zone,
    location_id bigint,
    phone character varying(15) NOT NULL,
    updated_at timestamp with time zone,
    avg_rating double precision NOT NULL
);


ALTER TABLE public.services_service OWNER TO postgres;

--
-- Name: services_service_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_service ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_service_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_serviceproviderapplication; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_serviceproviderapplication (
    id bigint NOT NULL,
    "otherType" character varying(50),
    national_identity_front character varying(100) NOT NULL,
    national_identity_back character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    location_id bigint NOT NULL,
    user_id bigint NOT NULL,
    service_type_id bigint,
    created_at timestamp with time zone,
    name character varying(255) NOT NULL,
    phone character varying(15) NOT NULL
);


ALTER TABLE public.services_serviceproviderapplication OWNER TO postgres;

--
-- Name: services_serviceproviderapplication_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_serviceproviderapplication ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_serviceproviderapplication_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_servicetype; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_servicetype (
    id bigint NOT NULL,
    type character varying(255) NOT NULL
);


ALTER TABLE public.services_servicetype OWNER TO postgres;

--
-- Name: services_servicetype_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_servicetype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_servicetype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_venue; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_venue (
    service_ptr_id bigint NOT NULL,
    hourly_rate numeric(10,2),
    capacity integer,
    amenities text
);


ALTER TABLE public.services_venue OWNER TO postgres;

--
-- Name: videos_video; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.videos_video (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    file character varying(100) NOT NULL,
    uploaded_at timestamp with time zone NOT NULL,
    service_id bigint
);


ALTER TABLE public.videos_video OWNER TO postgres;

--
-- Name: videos_video_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.videos_video ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.videos_video_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallet_transaction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wallet_transaction (
    id bigint NOT NULL,
    amount numeric(20,2) NOT NULL,
    transaction_type character varying(10) NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    made_at timestamp with time zone NOT NULL,
    wallet_id bigint NOT NULL
);


ALTER TABLE public.wallet_transaction OWNER TO postgres;

--
-- Name: wallet_transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wallet_transaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallet_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallet_wallet; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wallet_wallet (
    id bigint NOT NULL,
    balance numeric(20,3) NOT NULL,
    currency character varying(3) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.wallet_wallet OWNER TO postgres;

--
-- Name: wallet_wallet_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wallet_wallet ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallet_wallet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_emailverified accounts_emailverified_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_emailverified
    ADD CONSTRAINT accounts_emailverified_code_key UNIQUE (verfication_token);


--
-- Name: accounts_emailverified accounts_emailverified_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_emailverified
    ADD CONSTRAINT accounts_emailverified_pkey PRIMARY KEY (id);


--
-- Name: accounts_emailverified accounts_emailverified_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_emailverified
    ADD CONSTRAINT accounts_emailverified_user_id_key UNIQUE (user_id);


--
-- Name: accounts_otp accounts_otp_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_otp
    ADD CONSTRAINT accounts_otp_pkey PRIMARY KEY (id);


--
-- Name: accounts_passwordchangerequested accounts_passwordchangerequested_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_passwordchangerequested
    ADD CONSTRAINT accounts_passwordchangerequested_pkey PRIMARY KEY (id);


--
-- Name: accounts_user accounts_user_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_email_key UNIQUE (email);


--
-- Name: accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: events_event events_event_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events_event
    ADD CONSTRAINT events_event_pkey PRIMARY KEY (id);


--
-- Name: events_eventtype events_eventtype_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events_eventtype
    ADD CONSTRAINT events_eventtype_pkey PRIMARY KEY (id);


--
-- Name: events_invitationcard events_invitationcard_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events_invitationcard
    ADD CONSTRAINT events_invitationcard_pkey PRIMARY KEY (id);


--
-- Name: events_reservation events_reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events_reservation
    ADD CONSTRAINT events_reservation_pkey PRIMARY KEY (id);


--
-- Name: locations_address locations_address_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.locations_address
    ADD CONSTRAINT locations_address_pkey PRIMARY KEY (id);


--
-- Name: locations_location locations_location_latitude_longitude_address_id_dce5f1db_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.locations_location
    ADD CONSTRAINT locations_location_latitude_longitude_address_id_dce5f1db_uniq UNIQUE (latitude, longitude, address_id);


--
-- Name: locations_location locations_location_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.locations_location
    ADD CONSTRAINT locations_location_pkey PRIMARY KEY (id);


--
-- Name: notifications_message notifications_message_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications_message
    ADD CONSTRAINT notifications_message_pkey PRIMARY KEY (id);


--
-- Name: notifications_notification notifications_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications_notification
    ADD CONSTRAINT notifications_notification_pkey PRIMARY KEY (id);


--
-- Name: photos_decorphotos photos_decorphotos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photos_decorphotos
    ADD CONSTRAINT photos_decorphotos_pkey PRIMARY KEY (id);


--
-- Name: photos_foodphotos photos_foodphotos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photos_foodphotos
    ADD CONSTRAINT photos_foodphotos_pkey PRIMARY KEY (id);


--
-- Name: photos_maindecorphoto photos_maindecorphoto_decor_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photos_maindecorphoto
    ADD CONSTRAINT photos_maindecorphoto_decor_id_key UNIQUE (decor_id);


--
-- Name: photos_maindecorphoto photos_maindecorphoto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photos_maindecorphoto
    ADD CONSTRAINT photos_maindecorphoto_pkey PRIMARY KEY (id);


--
-- Name: photos_mainfoodphoto photos_mainfoodphoto_food_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photos_mainfoodphoto
    ADD CONSTRAINT photos_mainfoodphoto_food_id_key UNIQUE (food_id);


--
-- Name: photos_mainfoodphoto photos_mainfoodphoto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photos_mainfoodphoto
    ADD CONSTRAINT photos_mainfoodphoto_pkey PRIMARY KEY (id);


--
-- Name: photos_servicephotos photos_servicephotos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photos_servicephotos
    ADD CONSTRAINT photos_servicephotos_pkey PRIMARY KEY (id);


--
-- Name: photos_serviceprofilephoto photos_serviceprofilephoto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photos_serviceprofilephoto
    ADD CONSTRAINT photos_serviceprofilephoto_pkey PRIMARY KEY (id);


--
-- Name: photos_serviceprofilephoto photos_serviceprofilephoto_service_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photos_serviceprofilephoto
    ADD CONSTRAINT photos_serviceprofilephoto_service_id_key UNIQUE (service_id);


--
-- Name: reports_reportreview reports_reportreview_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports_reportreview
    ADD CONSTRAINT reports_reportreview_pkey PRIMARY KEY (id);


--
-- Name: reports_reportservice reports_reportservice_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports_reportservice
    ADD CONSTRAINT reports_reportservice_pkey PRIMARY KEY (id);


--
-- Name: reviews_review reviews_review_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews_review
    ADD CONSTRAINT reviews_review_pkey PRIMARY KEY (id);


--
-- Name: services_booking services_booking_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_booking
    ADD CONSTRAINT services_booking_pkey PRIMARY KEY (id);


--
-- Name: services_decor services_decor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_decor
    ADD CONSTRAINT services_decor_pkey PRIMARY KEY (id);


--
-- Name: services_decorationservice services_decorationservice_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_decorationservice
    ADD CONSTRAINT services_decorationservice_pkey PRIMARY KEY (service_ptr_id);


--
-- Name: services_decoreventtype services_decoretype_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_decoreventtype
    ADD CONSTRAINT services_decoretype_pkey PRIMARY KEY (id);


--
-- Name: services_djservice services_djservice_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_djservice
    ADD CONSTRAINT services_djservice_pkey PRIMARY KEY (service_ptr_id);


--
-- Name: services_entertainementservice services_entertainementservice_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_entertainementservice
    ADD CONSTRAINT services_entertainementservice_pkey PRIMARY KEY (service_ptr_id);


--
-- Name: services_favoriteservice services_favoriteservice_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_favoriteservice
    ADD CONSTRAINT services_favoriteservice_pkey PRIMARY KEY (id);


--
-- Name: services_favoriteservice services_favoriteservice_user_id_service_id_e70308d3_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_favoriteservice
    ADD CONSTRAINT services_favoriteservice_user_id_service_id_e70308d3_uniq UNIQUE (user_id, service_id);


--
-- Name: services_food services_food_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_food
    ADD CONSTRAINT services_food_pkey PRIMARY KEY (id);


--
-- Name: services_foodservice services_foodservice_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_foodservice
    ADD CONSTRAINT services_foodservice_pkey PRIMARY KEY (service_ptr_id);


--
-- Name: services_foodservicefood services_foodservicefood_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_foodservicefood
    ADD CONSTRAINT services_foodservicefood_pkey PRIMARY KEY (id);


--
-- Name: services_foodtype services_foodtype_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_foodtype
    ADD CONSTRAINT services_foodtype_pkey PRIMARY KEY (id);


--
-- Name: services_foodtypeservice services_foodtypeservice_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_foodtypeservice
    ADD CONSTRAINT services_foodtypeservice_pkey PRIMARY KEY (id);


--
-- Name: services_photographerservice services_photographerservice_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_photographerservice
    ADD CONSTRAINT services_photographerservice_pkey PRIMARY KEY (service_ptr_id);


--
-- Name: services_service services_service_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_service
    ADD CONSTRAINT services_service_pkey PRIMARY KEY (id);


--
-- Name: services_service services_service_service_provider_id_57311855_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_service
    ADD CONSTRAINT services_service_service_provider_id_57311855_uniq UNIQUE (service_provider_id);


--
-- Name: services_serviceproviderapplication services_serviceproviderapplication_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_serviceproviderapplication
    ADD CONSTRAINT services_serviceproviderapplication_pkey PRIMARY KEY (id);


--
-- Name: services_servicetype services_servicetype_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_servicetype
    ADD CONSTRAINT services_servicetype_pkey PRIMARY KEY (id);


--
-- Name: services_servicetype services_servicetype_type_c35141e5_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_servicetype
    ADD CONSTRAINT services_servicetype_type_c35141e5_uniq UNIQUE (type);


--
-- Name: services_venue services_venue_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_venue
    ADD CONSTRAINT services_venue_pkey PRIMARY KEY (service_ptr_id);


--
-- Name: reviews_review unique_user_service; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews_review
    ADD CONSTRAINT unique_user_service UNIQUE (user_id, service_id);


--
-- Name: videos_video videos_video_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.videos_video
    ADD CONSTRAINT videos_video_pkey PRIMARY KEY (id);


--
-- Name: wallet_transaction wallet_transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_transaction
    ADD CONSTRAINT wallet_transaction_pkey PRIMARY KEY (id);


--
-- Name: wallet_wallet wallet_wallet_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_wallet
    ADD CONSTRAINT wallet_wallet_pkey PRIMARY KEY (id);


--
-- Name: wallet_wallet wallet_wallet_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_wallet
    ADD CONSTRAINT wallet_wallet_user_id_key UNIQUE (user_id);


--
-- Name: accounts_emailverified_code_67f43061_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_emailverified_code_67f43061_like ON public.accounts_emailverified USING btree (verfication_token varchar_pattern_ops);


--
-- Name: accounts_otp_service_id_adb67fd0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_otp_service_id_adb67fd0 ON public.accounts_otp USING btree (service_id);


--
-- Name: accounts_otp_user_id_7275536e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_otp_user_id_7275536e ON public.accounts_otp USING btree (user_id);


--
-- Name: accounts_passwordchangerequested_user_id_ead277d1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_passwordchangerequested_user_id_ead277d1 ON public.accounts_passwordchangerequested USING btree (user_id);


--
-- Name: accounts_user_email_b2644a56_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_email_b2644a56_like ON public.accounts_user USING btree (email varchar_pattern_ops);


--
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);


--
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


--
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);


--
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: events_event_event_type_id_000b97e2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX events_event_event_type_id_000b97e2 ON public.events_event USING btree (event_type_id);


--
-- Name: events_event_location_id_2fb4171f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX events_event_location_id_2fb4171f ON public.events_event USING btree (location_id);


--
-- Name: events_event_user_id_39865209; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX events_event_user_id_39865209 ON public.events_event USING btree (user_id);


--
-- Name: events_invitationcard_event_id_4c173a5f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX events_invitationcard_event_id_4c173a5f ON public.events_invitationcard USING btree (event_id);


--
-- Name: events_reservation_event_id_3f3c413e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX events_reservation_event_id_3f3c413e ON public.events_reservation USING btree (event_id);


--
-- Name: events_reservation_service_id_4084838e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX events_reservation_service_id_4084838e ON public.events_reservation USING btree (service_id);


--
-- Name: locations_location_address_id_8cacc43c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX locations_location_address_id_8cacc43c ON public.locations_location USING btree (address_id);


--
-- Name: notifications_notification_dest_id_7316740b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX notifications_notification_dest_id_7316740b ON public.notifications_notification USING btree (dest_id);


--
-- Name: notifications_notification_message_id_32639e63; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX notifications_notification_message_id_32639e63 ON public.notifications_notification USING btree (message_id);


--
-- Name: notifications_notification_source_id_aeaf814a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX notifications_notification_source_id_aeaf814a ON public.notifications_notification USING btree (source_id);


--
-- Name: photos_decorphotos_decor_id_010867aa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX photos_decorphotos_decor_id_010867aa ON public.photos_decorphotos USING btree (decor_id);


--
-- Name: photos_foodphotos_food_id_9fce6ad8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX photos_foodphotos_food_id_9fce6ad8 ON public.photos_foodphotos USING btree (food_id);


--
-- Name: photos_maindecorphoto_decorPhoto_id_c31ea55f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "photos_maindecorphoto_decorPhoto_id_c31ea55f" ON public.photos_maindecorphoto USING btree ("decorPhoto_id");


--
-- Name: photos_mainfoodphoto_foodPhoto_id_02d5d65d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "photos_mainfoodphoto_foodPhoto_id_02d5d65d" ON public.photos_mainfoodphoto USING btree ("foodPhoto_id");


--
-- Name: photos_servicephotos_service_id_fe648005; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX photos_servicephotos_service_id_fe648005 ON public.photos_servicephotos USING btree (service_id);


--
-- Name: photos_serviceprofilephoto_servicePhoto_id_92fba400; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "photos_serviceprofilephoto_servicePhoto_id_92fba400" ON public.photos_serviceprofilephoto USING btree ("servicePhoto_id");


--
-- Name: reports_reportreview_reporter_id_a5c5c74b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reports_reportreview_reporter_id_a5c5c74b ON public.reports_reportreview USING btree (reporter_id);


--
-- Name: reports_reportreview_review_id_7592b430; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reports_reportreview_review_id_7592b430 ON public.reports_reportreview USING btree (review_id);


--
-- Name: reports_reportreview_solved_by_id_6c44d6aa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reports_reportreview_solved_by_id_6c44d6aa ON public.reports_reportreview USING btree (solved_by_id);


--
-- Name: reports_reportservice_reporter_id_0d9e97a4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reports_reportservice_reporter_id_0d9e97a4 ON public.reports_reportservice USING btree (reporter_id);


--
-- Name: reports_reportservice_service_id_63e997fb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reports_reportservice_service_id_63e997fb ON public.reports_reportservice USING btree (service_id);


--
-- Name: reports_reportservice_solved_by_id_2947acad; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reports_reportservice_solved_by_id_2947acad ON public.reports_reportservice USING btree (solved_by_id);


--
-- Name: reviews_review_service_id_8aaf292d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reviews_review_service_id_8aaf292d ON public.reviews_review USING btree (service_id);


--
-- Name: reviews_review_user_id_875caff2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reviews_review_user_id_875caff2 ON public.reviews_review USING btree (user_id);


--
-- Name: services_booking_service_id_cc6fde61; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_booking_service_id_cc6fde61 ON public.services_booking USING btree (service_id);


--
-- Name: services_booking_user_id_58c4e678; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_booking_user_id_58c4e678 ON public.services_booking USING btree (user_id);


--
-- Name: services_decor_decor_service_id_b992dd0b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_decor_decor_service_id_b992dd0b ON public.services_decor USING btree (decor_service_id);


--
-- Name: services_decoretype_event_type_id_bf5ceab8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_decoretype_event_type_id_bf5ceab8 ON public.services_decoreventtype USING btree (event_type_id);


--
-- Name: services_decoreventtype_decor_id_7f51918f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_decoreventtype_decor_id_7f51918f ON public.services_decoreventtype USING btree (decor_id);


--
-- Name: services_favoriteservice_service_id_5bc1a897; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_favoriteservice_service_id_5bc1a897 ON public.services_favoriteservice USING btree (service_id);


--
-- Name: services_favoriteservice_user_id_ffc4eafc; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_favoriteservice_user_id_ffc4eafc ON public.services_favoriteservice USING btree (user_id);


--
-- Name: services_food_food_type_id_1b8bcbb2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_food_food_type_id_1b8bcbb2 ON public.services_food USING btree (food_type_id);


--
-- Name: services_foodservicefood_foodService_id_3f626fac; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "services_foodservicefood_foodService_id_3f626fac" ON public.services_foodservicefood USING btree ("foodService_id");


--
-- Name: services_foodservicefood_food_id_74f2d95e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_foodservicefood_food_id_74f2d95e ON public.services_foodservicefood USING btree (food_id);


--
-- Name: services_foodtypeservice_foodService_id_51a35d99; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "services_foodtypeservice_foodService_id_51a35d99" ON public.services_foodtypeservice USING btree ("foodService_id");


--
-- Name: services_foodtypeservice_foodType_id_df207344; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "services_foodtypeservice_foodType_id_df207344" ON public.services_foodtypeservice USING btree ("foodType_id");


--
-- Name: services_service_location_id_e1ea4563; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_service_location_id_e1ea4563 ON public.services_service USING btree (location_id);


--
-- Name: services_service_service_type_id_6d1ff243; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_service_service_type_id_6d1ff243 ON public.services_service USING btree (service_type_id);


--
-- Name: services_serviceproviderapplication_location_id_1a4b14d0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_serviceproviderapplication_location_id_1a4b14d0 ON public.services_serviceproviderapplication USING btree (location_id);


--
-- Name: services_serviceproviderapplication_serviceType_id_416dae00; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "services_serviceproviderapplication_serviceType_id_416dae00" ON public.services_serviceproviderapplication USING btree (service_type_id);


--
-- Name: services_serviceproviderapplication_user_id_56ee8352; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_serviceproviderapplication_user_id_56ee8352 ON public.services_serviceproviderapplication USING btree (user_id);


--
-- Name: services_servicetype_type_c35141e5_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_servicetype_type_c35141e5_like ON public.services_servicetype USING btree (type varchar_pattern_ops);


--
-- Name: videos_video_service_id_f711e186; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX videos_video_service_id_f711e186 ON public.videos_video USING btree (service_id);


--
-- Name: wallet_transaction_wallet_id_a0ff1b17; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wallet_transaction_wallet_id_a0ff1b17 ON public.wallet_transaction USING btree (wallet_id);


--
-- Name: accounts_emailverified accounts_emailverified_user_id_7fda26cf_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_emailverified
    ADD CONSTRAINT accounts_emailverified_user_id_7fda26cf_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_otp accounts_otp_service_id_adb67fd0_fk_services_service_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_otp
    ADD CONSTRAINT accounts_otp_service_id_adb67fd0_fk_services_service_id FOREIGN KEY (service_id) REFERENCES public.services_service(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_otp accounts_otp_user_id_7275536e_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_otp
    ADD CONSTRAINT accounts_otp_user_id_7275536e_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_passwordchangerequested accounts_passwordcha_user_id_ead277d1_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_passwordchangerequested
    ADD CONSTRAINT accounts_passwordcha_user_id_ead277d1_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: events_event events_event_event_type_id_000b97e2_fk_events_eventtype_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events_event
    ADD CONSTRAINT events_event_event_type_id_000b97e2_fk_events_eventtype_id FOREIGN KEY (event_type_id) REFERENCES public.events_eventtype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: events_event events_event_location_id_2fb4171f_fk_locations_location_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events_event
    ADD CONSTRAINT events_event_location_id_2fb4171f_fk_locations_location_id FOREIGN KEY (location_id) REFERENCES public.locations_location(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: events_event events_event_user_id_39865209_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events_event
    ADD CONSTRAINT events_event_user_id_39865209_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: events_invitationcard events_invitationcard_event_id_4c173a5f_fk_events_event_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events_invitationcard
    ADD CONSTRAINT events_invitationcard_event_id_4c173a5f_fk_events_event_id FOREIGN KEY (event_id) REFERENCES public.events_event(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: events_reservation events_reservation_event_id_3f3c413e_fk_events_event_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events_reservation
    ADD CONSTRAINT events_reservation_event_id_3f3c413e_fk_events_event_id FOREIGN KEY (event_id) REFERENCES public.events_event(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: events_reservation events_reservation_service_id_4084838e_fk_services_service_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events_reservation
    ADD CONSTRAINT events_reservation_service_id_4084838e_fk_services_service_id FOREIGN KEY (service_id) REFERENCES public.services_service(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: locations_location locations_location_address_id_8cacc43c_fk_locations_address_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.locations_location
    ADD CONSTRAINT locations_location_address_id_8cacc43c_fk_locations_address_id FOREIGN KEY (address_id) REFERENCES public.locations_address(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notifications_notification notifications_notifi_message_id_32639e63_fk_notificat; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications_notification
    ADD CONSTRAINT notifications_notifi_message_id_32639e63_fk_notificat FOREIGN KEY (message_id) REFERENCES public.notifications_message(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notifications_notification notifications_notifi_source_id_aeaf814a_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications_notification
    ADD CONSTRAINT notifications_notifi_source_id_aeaf814a_fk_accounts_ FOREIGN KEY (source_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notifications_notification notifications_notification_dest_id_7316740b_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications_notification
    ADD CONSTRAINT notifications_notification_dest_id_7316740b_fk_accounts_user_id FOREIGN KEY (dest_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: photos_decorphotos photos_decorphotos_decor_id_010867aa_fk_services_decor_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photos_decorphotos
    ADD CONSTRAINT photos_decorphotos_decor_id_010867aa_fk_services_decor_id FOREIGN KEY (decor_id) REFERENCES public.services_decor(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: photos_foodphotos photos_foodphotos_food_id_9fce6ad8_fk_services_food_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photos_foodphotos
    ADD CONSTRAINT photos_foodphotos_food_id_9fce6ad8_fk_services_food_id FOREIGN KEY (food_id) REFERENCES public.services_food(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: photos_maindecorphoto photos_maindecorphot_decorPhoto_id_c31ea55f_fk_photos_de; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photos_maindecorphoto
    ADD CONSTRAINT "photos_maindecorphot_decorPhoto_id_c31ea55f_fk_photos_de" FOREIGN KEY ("decorPhoto_id") REFERENCES public.photos_decorphotos(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: photos_maindecorphoto photos_maindecorphoto_decor_id_e459a88e_fk_services_decor_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photos_maindecorphoto
    ADD CONSTRAINT photos_maindecorphoto_decor_id_e459a88e_fk_services_decor_id FOREIGN KEY (decor_id) REFERENCES public.services_decor(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: photos_mainfoodphoto photos_mainfoodphoto_foodPhoto_id_02d5d65d_fk_photos_fo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photos_mainfoodphoto
    ADD CONSTRAINT "photos_mainfoodphoto_foodPhoto_id_02d5d65d_fk_photos_fo" FOREIGN KEY ("foodPhoto_id") REFERENCES public.photos_foodphotos(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: photos_mainfoodphoto photos_mainfoodphoto_food_id_36d05f70_fk_services_food_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photos_mainfoodphoto
    ADD CONSTRAINT photos_mainfoodphoto_food_id_36d05f70_fk_services_food_id FOREIGN KEY (food_id) REFERENCES public.services_food(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: photos_servicephotos photos_servicephotos_service_id_fe648005_fk_services_service_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photos_servicephotos
    ADD CONSTRAINT photos_servicephotos_service_id_fe648005_fk_services_service_id FOREIGN KEY (service_id) REFERENCES public.services_service(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: photos_serviceprofilephoto photos_serviceprofil_servicePhoto_id_92fba400_fk_photos_se; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photos_serviceprofilephoto
    ADD CONSTRAINT "photos_serviceprofil_servicePhoto_id_92fba400_fk_photos_se" FOREIGN KEY ("servicePhoto_id") REFERENCES public.photos_servicephotos(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: photos_serviceprofilephoto photos_serviceprofil_service_id_7e687b81_fk_services_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photos_serviceprofilephoto
    ADD CONSTRAINT photos_serviceprofil_service_id_7e687b81_fk_services_ FOREIGN KEY (service_id) REFERENCES public.services_service(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reports_reportreview reports_reportreview_reporter_id_a5c5c74b_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports_reportreview
    ADD CONSTRAINT reports_reportreview_reporter_id_a5c5c74b_fk_accounts_user_id FOREIGN KEY (reporter_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reports_reportreview reports_reportreview_review_id_7592b430_fk_reviews_review_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports_reportreview
    ADD CONSTRAINT reports_reportreview_review_id_7592b430_fk_reviews_review_id FOREIGN KEY (review_id) REFERENCES public.reviews_review(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reports_reportreview reports_reportreview_solved_by_id_6c44d6aa_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports_reportreview
    ADD CONSTRAINT reports_reportreview_solved_by_id_6c44d6aa_fk_accounts_user_id FOREIGN KEY (solved_by_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reports_reportservice reports_reportservic_service_id_63e997fb_fk_services_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports_reportservice
    ADD CONSTRAINT reports_reportservic_service_id_63e997fb_fk_services_ FOREIGN KEY (service_id) REFERENCES public.services_service(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reports_reportservice reports_reportservice_reporter_id_0d9e97a4_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports_reportservice
    ADD CONSTRAINT reports_reportservice_reporter_id_0d9e97a4_fk_accounts_user_id FOREIGN KEY (reporter_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reports_reportservice reports_reportservice_solved_by_id_2947acad_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports_reportservice
    ADD CONSTRAINT reports_reportservice_solved_by_id_2947acad_fk_accounts_user_id FOREIGN KEY (solved_by_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reviews_review reviews_review_service_id_8aaf292d_fk_services_service_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews_review
    ADD CONSTRAINT reviews_review_service_id_8aaf292d_fk_services_service_id FOREIGN KEY (service_id) REFERENCES public.services_service(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reviews_review reviews_review_user_id_875caff2_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews_review
    ADD CONSTRAINT reviews_review_user_id_875caff2_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_booking services_booking_service_id_cc6fde61_fk_services_service_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_booking
    ADD CONSTRAINT services_booking_service_id_cc6fde61_fk_services_service_id FOREIGN KEY (service_id) REFERENCES public.services_service(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_booking services_booking_user_id_58c4e678_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_booking
    ADD CONSTRAINT services_booking_user_id_58c4e678_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_decor services_decor_decor_service_id_b992dd0b_fk_services_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_decor
    ADD CONSTRAINT services_decor_decor_service_id_b992dd0b_fk_services_ FOREIGN KEY (decor_service_id) REFERENCES public.services_decorationservice(service_ptr_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_decorationservice services_decorations_service_ptr_id_0caf2c7a_fk_services_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_decorationservice
    ADD CONSTRAINT services_decorations_service_ptr_id_0caf2c7a_fk_services_ FOREIGN KEY (service_ptr_id) REFERENCES public.services_service(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_decoreventtype services_decoretype_event_type_id_bf5ceab8_fk_events_ev; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_decoreventtype
    ADD CONSTRAINT services_decoretype_event_type_id_bf5ceab8_fk_events_ev FOREIGN KEY (event_type_id) REFERENCES public.events_eventtype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_decoreventtype services_decoreventtype_decor_id_7f51918f_fk_services_decor_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_decoreventtype
    ADD CONSTRAINT services_decoreventtype_decor_id_7f51918f_fk_services_decor_id FOREIGN KEY (decor_id) REFERENCES public.services_decor(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_djservice services_djservice_service_ptr_id_c7eab6ea_fk_services_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_djservice
    ADD CONSTRAINT services_djservice_service_ptr_id_c7eab6ea_fk_services_ FOREIGN KEY (service_ptr_id) REFERENCES public.services_service(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_entertainementservice services_entertainem_service_ptr_id_45ee38ac_fk_services_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_entertainementservice
    ADD CONSTRAINT services_entertainem_service_ptr_id_45ee38ac_fk_services_ FOREIGN KEY (service_ptr_id) REFERENCES public.services_service(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_favoriteservice services_favoriteser_service_id_5bc1a897_fk_services_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_favoriteservice
    ADD CONSTRAINT services_favoriteser_service_id_5bc1a897_fk_services_ FOREIGN KEY (service_id) REFERENCES public.services_service(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_favoriteservice services_favoriteservice_user_id_ffc4eafc_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_favoriteservice
    ADD CONSTRAINT services_favoriteservice_user_id_ffc4eafc_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_food services_food_food_type_id_1b8bcbb2_fk_services_foodtype_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_food
    ADD CONSTRAINT services_food_food_type_id_1b8bcbb2_fk_services_foodtype_id FOREIGN KEY (food_type_id) REFERENCES public.services_foodtype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_foodservicefood services_foodservice_foodService_id_3f626fac_fk_services_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_foodservicefood
    ADD CONSTRAINT "services_foodservice_foodService_id_3f626fac_fk_services_" FOREIGN KEY ("foodService_id") REFERENCES public.services_foodservice(service_ptr_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_foodservice services_foodservice_service_ptr_id_3492bad4_fk_services_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_foodservice
    ADD CONSTRAINT services_foodservice_service_ptr_id_3492bad4_fk_services_ FOREIGN KEY (service_ptr_id) REFERENCES public.services_service(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_foodservicefood services_foodservicefood_food_id_74f2d95e_fk_services_food_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_foodservicefood
    ADD CONSTRAINT services_foodservicefood_food_id_74f2d95e_fk_services_food_id FOREIGN KEY (food_id) REFERENCES public.services_food(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_foodtypeservice services_foodtypeser_foodService_id_51a35d99_fk_services_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_foodtypeservice
    ADD CONSTRAINT "services_foodtypeser_foodService_id_51a35d99_fk_services_" FOREIGN KEY ("foodService_id") REFERENCES public.services_foodservice(service_ptr_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_foodtypeservice services_foodtypeser_foodType_id_df207344_fk_services_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_foodtypeservice
    ADD CONSTRAINT "services_foodtypeser_foodType_id_df207344_fk_services_" FOREIGN KEY ("foodType_id") REFERENCES public.services_foodtype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_photographerservice services_photographe_service_ptr_id_83ddeb9d_fk_services_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_photographerservice
    ADD CONSTRAINT services_photographe_service_ptr_id_83ddeb9d_fk_services_ FOREIGN KEY (service_ptr_id) REFERENCES public.services_service(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_service services_service_location_id_e1ea4563_fk_locations_location_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_service
    ADD CONSTRAINT services_service_location_id_e1ea4563_fk_locations_location_id FOREIGN KEY (location_id) REFERENCES public.locations_location(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_service services_service_service_provider_id_57311855_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_service
    ADD CONSTRAINT services_service_service_provider_id_57311855_fk_accounts_ FOREIGN KEY (service_provider_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_service services_service_service_type_id_6d1ff243_fk_services_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_service
    ADD CONSTRAINT services_service_service_type_id_6d1ff243_fk_services_ FOREIGN KEY (service_type_id) REFERENCES public.services_servicetype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_serviceproviderapplication services_serviceprov_location_id_1a4b14d0_fk_locations; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_serviceproviderapplication
    ADD CONSTRAINT services_serviceprov_location_id_1a4b14d0_fk_locations FOREIGN KEY (location_id) REFERENCES public.locations_location(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_serviceproviderapplication services_serviceprov_service_type_id_79e3c82d_fk_services_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_serviceproviderapplication
    ADD CONSTRAINT services_serviceprov_service_type_id_79e3c82d_fk_services_ FOREIGN KEY (service_type_id) REFERENCES public.services_servicetype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_serviceproviderapplication services_serviceprov_user_id_56ee8352_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_serviceproviderapplication
    ADD CONSTRAINT services_serviceprov_user_id_56ee8352_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_venue services_venue_service_ptr_id_b911dade_fk_services_service_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_venue
    ADD CONSTRAINT services_venue_service_ptr_id_b911dade_fk_services_service_id FOREIGN KEY (service_ptr_id) REFERENCES public.services_service(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: videos_video videos_video_service_id_f711e186_fk_services_service_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.videos_video
    ADD CONSTRAINT videos_video_service_id_f711e186_fk_services_service_id FOREIGN KEY (service_id) REFERENCES public.services_service(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wallet_transaction wallet_transaction_wallet_id_a0ff1b17_fk_wallet_wallet_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_transaction
    ADD CONSTRAINT wallet_transaction_wallet_id_a0ff1b17_fk_wallet_wallet_id FOREIGN KEY (wallet_id) REFERENCES public.wallet_wallet(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wallet_wallet wallet_wallet_user_id_8c75caaa_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_wallet
    ADD CONSTRAINT wallet_wallet_user_id_8c75caaa_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


--
-- PostgreSQL database dump complete
--

