# Generated by Django 5.0.6 on 2024-06-03 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_rename_city_address_place_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='place_name',
            new_name='village_city',
        ),
    ]
