# Generated by Django 5.0.6 on 2024-07-25 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_updated_at_alter_review_service'),
        ('services', '0022_service_avg_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'service'), name='unique_user_service'),
        ),
    ]
