# Generated by Django 5.0.6 on 2024-06-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_foodphotos_servicephotos_delete_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodphotos',
            name='url',
            field=models.ImageField(upload_to='storage/pictures/foods/'),
        ),
        migrations.AlterField(
            model_name='servicephotos',
            name='url',
            field=models.ImageField(upload_to='storage/pictures/services/'),
        ),
    ]
