# Generated by Django 5.0.6 on 2024-07-01 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_foodphotos_url_alter_servicephotos_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodphotos',
            old_name='url',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='servicephotos',
            old_name='url',
            new_name='image',
        ),
    ]
