# Generated by Django 5.0.6 on 2024-07-05 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_rename_url_foodphotos_image_and_more'),
        ('services', '0012_alter_service_service_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodphotos',
            name='image',
            field=models.ImageField(upload_to='pictures/foods/'),
        ),
        migrations.AlterField(
            model_name='servicephotos',
            name='image',
            field=models.ImageField(upload_to='pictures/services/'),
        ),
        migrations.CreateModel(
            name='ServiceProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('servicePhoto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.servicephotos')),
            ],
        ),
    ]
