# Generated by Django 5.0.6 on 2024-07-16 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_alter_foodphotos_image_alter_servicephotos_image_and_more'),
        ('services', '0013_remove_decorationservice_hourly_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainFoodPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.food')),
                ('foodPhoto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.foodphotos')),
            ],
        ),
    ]
