# Generated by Django 5.0.6 on 2024-07-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_decorphotos_decor_maindecorphoto_decor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decorphotos',
            name='image',
            field=models.ImageField(upload_to='pictures/decors/'),
        ),
    ]
