# Generated by Django 5.0.6 on 2024-07-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_alter_decorphotos_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprofilephoto',
            name='servicePhoto',
        ),
        migrations.AddField(
            model_name='serviceprofilephoto',
            name='image',
            field=models.ImageField(default='pictures/services/profile_photos/dam.jfif', upload_to='pictures/services/profile_photos'),
            preserve_default=False,
        ),
    ]
