# Generated by Django 5.0.6 on 2024-07-31 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_remove_serviceprofilephoto_servicephoto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprofilephoto',
            old_name='image',
            new_name='servicePhoto',
        ),
    ]
