# Generated by Django 5.0.6 on 2024-05-27 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_hourly_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FoodTypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.foodservice')),
                ('foodType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.foodtype')),
            ],
        ),
    ]
