# Generated by Django 5.0.6 on 2024-05-29 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_foodtype_foodtypeservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodservice',
            name='cuisine_type',
        ),
        migrations.RemoveField(
            model_name='foodservice',
            name='menu',
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.foodtype')),
            ],
        ),
        migrations.CreateModel(
            name='FoodServiceFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.food')),
                ('foodService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.foodservice')),
            ],
        ),
    ]
