# Generated by Django 5.0.6 on 2024-05-29 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_food_gradients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='gradients',
            new_name='ingredients',
        ),
    ]
