# Generated by Django 5.0.6 on 2024-06-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_decoration_venue_foodservice_area_limit_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
