# Generated by Django 5.0.6 on 2024-06-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodservice',
            name='area_limit_km',
            field=models.IntegerField(null=True),
        ),
    ]
