# Generated by Django 5.0.6 on 2024-06-04 23:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_foodservice_area_limit_km'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoriteservice',
            unique_together={('user', 'service')},
        ),
    ]
