# Generated by Django 5.0.6 on 2024-06-07 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_other_type'),
        ('services', '0010_alter_favoriteservice_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecorationService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.service')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_limit_km', models.IntegerField()),
            ],
            bases=('services.service',),
        ),
        migrations.CreateModel(
            name='EntertainementService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.service')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_limit_km', models.IntegerField()),
            ],
            bases=('services.service',),
        ),
        migrations.CreateModel(
            name='PhotoGrapherService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.service')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_limit_km', models.IntegerField()),
            ],
            bases=('services.service',),
        ),
        migrations.CreateModel(
            name='Decore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('avialable_quantity', models.IntegerField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(upload_to='storage/pictures/decores/')),
                ('decore_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.decorationservice')),
            ],
        ),
        migrations.CreateModel(
            name='DecoreType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.decore')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventtype')),
            ],
        ),
        migrations.DeleteModel(
            name='Decoration',
        ),
    ]
