# Generated by Django 5.0.6 on 2024-07-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_remove_decorationservice_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djservice',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
