# Generated by Django 5.0.6 on 2024-07-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_djservice_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djservice',
            name='area_limit_km',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='djservice',
            name='equipment_provided',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='djservice',
            name='music_genre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
