# Generated by Django 5.0.6 on 2024-07-23 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_invitationcard'),
        ('services', '0017_alter_servicetype_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DecoreType',
            new_name='DecorEventType',
        ),
        migrations.RemoveField(
            model_name='decoreventtype',
            name='decore',
        ),
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('avialable_quantity', models.IntegerField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(null=True)),
                ('decor_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.decorationservice')),
            ],
        ),
        migrations.AddField(
            model_name='decoreventtype',
            name='decor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.decor'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Decore',
        ),
    ]
