# Generated by Django 5.0.6 on 2024-07-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_remove_decoreventtype_decore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decor',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
