# Generated by Django 5.0.6 on 2024-07-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_decor_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decor',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='decor',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
