# Generated by Django 5.0.6 on 2024-07-24 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_alter_decor_hourly_rate_alter_decor_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decor',
            old_name='avialable_quantity',
            new_name='available_quantity',
        ),
    ]
