# Generated by Django 5.0.6 on 2024-07-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_rename_avialable_quantity_decor_available_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
    ]
