# Generated by Django 5.0.6 on 2024-08-03 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_other_type_alter_event_total_cost_and_more'),
        ('services', '0023_decorsreservation_decorsinreservation_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decorsreservation',
            name='event',
        ),
        migrations.RemoveField(
            model_name='decorsreservation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='decorsreservation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='decorsreservation',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='servicereservation',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='servicereservation',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='servicereservation',
            name='event',
        ),
        migrations.RemoveField(
            model_name='servicereservation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='servicereservation',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='servicereservation',
            name='status',
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.AddField(
            model_name='decorsreservation',
            name='reservation_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.reservation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicereservation',
            name='reservation_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.reservation'),
            preserve_default=False,
        ),
    ]
