# Generated by Django 5.0.6 on 2024-08-15 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_alter_reservation_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DecorInOrder',
        ),
    ]
