# Generated by Django 5.0.6 on 2024-08-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_delete_decorinorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='decorsinreservation',
            name='end_time',
            field=models.DateTimeField(default='2020-02-13'),
            preserve_default=False,
        ),
    ]
