# Generated by Django 5.0.6 on 2024-08-15 12:33

import builtins
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_decorsinreservation_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(default="2024-08-20 15:00:00+03"),
            preserve_default=False,
        ),
    ]
