# Generated by Django 5.0.6 on 2024-06-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='other_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
