# Generated by Django 5.0.6 on 2024-08-16 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_invitationcarddesign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationcard',
            name='design',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.invitationcarddesign'),
            preserve_default=False,
        ),
    ]
