# Generated by Django 5.0.6 on 2024-05-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_verifycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifycode',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
