# Generated by Django 5.0.6 on 2024-07-01 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_emailverified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverified',
            old_name='code',
            new_name='verfication_token',
        ),
        migrations.AlterField(
            model_name='emailverified',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
