# Generated by Django 5.0.6 on 2024-07-01 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_code_emailverified_verfication_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverified',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 7, 38, 15, 297632, tzinfo=datetime.timezone.utc)),
        ),
    ]
