# Generated by Django 5.0.6 on 2024-07-01 07:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_emailverified_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverified',
            name='expire_date',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
