# Generated by Django 5.0.6 on 2024-07-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_emailverified_verification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverified',
            name='verification_date',
            field=models.DateTimeField(auto_now_add=True, default='1000-10-10'),
            preserve_default=False,
        ),
    ]
