# Generated by Django 5.0.6 on 2024-07-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_emailverified_verification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverified',
            name='verification_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
