# Generated by Django 5.0.6 on 2024-07-31 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='currency',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
