# Generated by Django 5.0.6 on 2024-08-03 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_remove_decorsreservation_event_and_more'),
        ('wallet', '0005_centerwallet_transaction_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.order'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.reservation'),
        ),
    ]
