# Generated by Django 5.0.6 on 2024-08-03 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_transaction_order_transaction_reservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='centerwallet',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='centerwallet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='centerwallet',
            name='id',
        ),
        migrations.RemoveField(
            model_name='centerwallet',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='centerwallet',
            name='wallet_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallet.wallet'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('wallet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallet.wallet')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('wallet.wallet',),
        ),
    ]
